# Generated by Django 4.0.3 on 2022-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choose',
            old_name='user',
            new_name='username',
        ),
    ]
