# Generated by Django 4.0.3 on 2022-04-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
