# Generated by Django 4.0.3 on 2022-04-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_poll_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='creator',
            field=models.IntegerField(default=1),
        ),
    ]
