# Generated by Django 4.0.3 on 2022-05-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_user_option_survey_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_y', models.IntegerField(default=1)),
                ('pub_n', models.IntegerField(default=1)),
                ('sec_a', models.IntegerField(default=1)),
                ('sec_x', models.IntegerField(default=1)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.survey')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
