# Generated by Django 4.0.3 on 2022-05-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_keys_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keys',
            new_name='Key',
        ),
    ]
