# Generated by Django 4.0.3 on 2022-05-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_keys_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='polls.survey'),
        ),
    ]
