# Generated by Django 4.0.3 on 2022-05-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_key_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='survey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='polls.survey'),
        ),
    ]
