# Generated by Django 4.0.3 on 2022-06-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_key_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='pub_n',
        ),
        migrations.RemoveField(
            model_name='key',
            name='pub_y',
        ),
        migrations.RemoveField(
            model_name='key',
            name='sec_a',
        ),
        migrations.RemoveField(
            model_name='key',
            name='sec_x',
        ),
        migrations.AddField(
            model_name='key',
            name='private_exponent',
            field=models.CharField(default=1, max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='private_key',
            field=models.CharField(default=1, max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='public_exponent',
            field=models.CharField(default=1, max_length=4096),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='public_key',
            field=models.CharField(default=1, max_length=4096),
            preserve_default=False,
        ),
    ]
