# Generated by Django 4.0.3 on 2022-06-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_answer_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='survey',
        ),
    ]
