# Generated by Django 4.0.3 on 2022-07-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_answer_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=70)),
                ('db_id', models.CharField(max_length=256)),
            ],
        ),
    ]
